#!/bin/bash

# Update and install required packages
sudo apt update
sudo apt install -y i3 polybar rofi firefox-esr code lightdm i3status dex xss-lock nm-applet pulseaudio-utils

# Register i3 as the default window manager
sudo update-alternatives --install /usr/bin/x-window-manager x-window-manager /usr/bin/i3 50
sudo update-alternatives --set x-window-manager /usr/bin/i3

# Set i3 as the default session manager
sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/i3 50
sudo update-alternatives --set x-session-manager /usr/bin/i3

# Enable LightDM for graphical login
sudo systemctl enable lightdm

# Configure LightDM for autologin
sudo sed -i '/^\[Seat:\*\]/a autologin-user='"$(whoami)"'\nautologin-user-timeout=0' /etc/lightdm/lightdm.conf

# Configure .xsession to start i3 automatically
echo "exec i3" > ~/.xsession
chmod +x ~/.xsession

# Setup polybar configuration
mkdir -p ~/.config/polybar
cat > ~/.config/polybar/config.ini <<EOL
[bar/kiosk]
width = 100%
height = 30
background = #222
foreground = #fff
font-0 = "Noto Sans:size=10"
modules-center = launcher

[module/launcher]
type = custom/text
content = "🚀 Launch Apps"
click-left = rofi -show drun
EOL

# Configure i3 with default settings and requested customizations
mkdir -p ~/.config/i3
cat > ~/.config/i3/config <<EOL
# This file has been auto-generated by i3-config-wizard(1).

set \$mod Mod4

font pango:monospace 8

exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet

set \$refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && \$refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && \$refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && \$refresh_i3status

floating_modifier \$mod

bindsym \$mod+Return exec i3-sensible-terminal
bindsym \$mod+Shift+q kill

bindsym \$mod+d exec --no-startup-id rofi -show drun
bindsym \$mod+space exec --no-startup-id rofi -show run
bindsym \$mod+Tab exec --no-startup-id rofi -show window

bindsym \$mod+j focus left
bindsym \$mod+k focus down
bindsym \$mod+l focus up
bindsym \$mod+semicolon focus right

bindsym \$mod+Shift+j move left
bindsym \$mod+Shift+k move down
bindsym \$mod+Shift+l move up
bindsym \$mod+Shift+semicolon move right

bindsym \$mod+h split h
bindsym \$mod+v split v

bindsym \$mod+f fullscreen toggle

bindsym \$mod+s layout stacking
bindsym \$mod+w layout tabbed
bindsym \$mod+e layout toggle split

bindsym \$mod+Shift+space floating toggle
bindsym \$mod+space focus mode_toggle

bindsym \$mod+a focus parent

bindsym \$mod+Shift+c reload
bindsym \$mod+Shift+r restart
bindsym \$mod+Shift+e exec "i3-nagbar -t warning -m 'Exit i3?' -B 'Yes' 'i3-msg exit'"

mode "resize" {
  bindsym j resize shrink width 10 px or 10 ppt
  bindsym k resize grow height 10 px or 10 ppt
  bindsym l resize shrink height 10 px or 10 ppt
  bindsym semicolon resize grow width 10 px or 10 ppt

  bindsym Left resize shrink width 10 px or 10 ppt
  bindsym Down resize grow height 10 px or 10 ppt
  bindsym Up resize shrink height 10 px or 10 ppt
  bindsym Right resize grow width 10 px or 10 ppt

  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym \$mod+r mode "default"
}

bindsym \$mod+r mode "resize"

bar {
  status_command i3status
}

exec_always --no-startup-id polybar kiosk

exec --no-startup-id firefox-esr
exec --no-startup-id linuxcnc ~/linuxcnc/configs/qtdragon/qtdragon.ini
exec --no-startup-id code

exec --no-startup-id xset s off
exec --no-startup-id xset s noblank
exec --no-startup-id xset -dpms
EOL

# Confirmation
printf "\ni3 kiosk setup complete. Reboot the system to apply changes.\n"
