package domain

import (
	"crypto/rand"
	"encoding/hex"
	"io"
)

const (
	IDEntropyBytes = 16
	IDLength       = IDEntropyBytes * 2
)

// NewID returns a cryptographically random 128-bit identifier encoded as
// fixed-width lowercase hexadecimal. It contains no user or path information.
func NewID() (string, error) {
	return newIDFrom(rand.Reader)
}

func newIDFrom(source io.Reader) (string, error) {
	raw := make([]byte, IDEntropyBytes)
	if _, err := io.ReadFull(source, raw); err != nil {
		return "", err
	}
	return hex.EncodeToString(raw), nil
}

func NewSetupID() (string, error)         { return NewID() }
func NewArtifactID() (string, error)      { return NewID() }
func NewStorageObjectID() (string, error) { return NewID() }
func NewValidationRunID() (string, error) { return NewID() }
func NewJobID() (string, error)           { return NewID() }
func NewImportID() (string, error)        { return NewID() }
func NewAuditEventID() (string, error)    { return NewID() }
func NewOperationID() (string, error)     { return NewID() }
func NewFolderID() (string, error)        { return NewID() }

// IsValidID accepts only the canonical representation generated by NewID.
func IsValidID(id string) bool {
	if len(id) != IDLength {
		return false
	}
	for i := range len(id) {
		if (id[i] < '0' || id[i] > '9') && (id[i] < 'a' || id[i] > 'f') {
			return false
		}
	}
	return true
}

func ValidateID(id string) error {
	if !IsValidID(id) {
		return NewError(CodeInvalidID, "identifier is not valid")
	}
	return nil
}
