---
- name: Enable user lingering
  ansible.builtin.command:
    argv:
      - /usr/bin/loginctl
      - enable-linger
      - --
      - "{{ target_user }}"
    creates: "/var/lib/systemd/linger/{{ target_user }}"
  become: true
